# Generated by Django 3.2.8 on 2022-06-21 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='linebotId',
            field=models.CharField(default='', max_length=255),
        ),
    ]
