# Generated by Django 3.2.8 on 2022-07-03 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_health'),
    ]

    operations = [
        migrations.DeleteModel(
            name='health',
        ),
    ]
