# Generated by Django 3.2.8 on 2022-07-03 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_delete_health'),
    ]

    operations = [
        migrations.CreateModel(
            name='health',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='', max_length=255)),
                ('price', models.IntegerField(default=0)),
                ('text', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
