# Generated by Django 3.2.8 on 2022-07-05 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_health'),
    ]

    operations = [
        migrations.CreateModel(
            name='HH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='', max_length=255)),
                ('price', models.IntegerField(default='')),
                ('Sdate', models.CharField(default='', max_length=255)),
                ('Edate', models.CharField(default='', max_length=255)),
                ('eg_name', models.CharField(default='', max_length=255)),
                ('ch_name', models.CharField(default='', max_length=255)),
                ('element', models.CharField(default='', max_length=255)),
                ('dose', models.CharField(default='', max_length=255)),
                ('company_name', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
