# Generated by Django 3.2.8 on 2022-09-22 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_cartdb_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='all',
            old_name='name_all',
            new_name='name',
        ),
    ]
