# Generated by Django 3.2.8 on 2022-09-24 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_cpu_chip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='all',
            old_name='name',
            new_name='name_all',
        ),
    ]
