# Generated by Django 3.2.8 on 2022-10-02 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_rename_name_all_name_all'),
    ]

    operations = [
        migrations.AddField(
            model_name='db',
            name='lineID',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='db',
            name='pc_images',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='db',
            name='url_list',
            field=models.CharField(default='', max_length=255),
        ),
    ]
