# Generated by Django 3.2.8 on 2022-10-02 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20221002_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='db',
            name='formID',
            field=models.CharField(default='', max_length=255),
        ),
    ]
