# Generated by Django 3.2.8 on 2022-10-03 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_db_formid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hdd',
            name='size',
            field=models.CharField(choices=[('action', '動作片'), ('romance', '愛情片'), ('drama', '劇情片')], default='', max_length=255),
        ),
    ]
