# Generated by Django 3.2.8 on 2022-10-03 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_auto_20221003_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='display',
            name='Memory',
            field=models.CharField(choices=[('4gb', '4gb'), ('8gb', '8gb'), ('12gb', '12gb'), ('16gb', '16gb'), ('24gb', '24gb')], default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='memory',
            name='type',
            field=models.CharField(choices=[('Desktop', '桌電'), ('Laptop', '筆電')], default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='power',
            name='Watts',
            field=models.IntegerField(default=''),
        ),
    ]
